mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('prueba.urls')),
]

handler404="prueba.views.mi_error_404"

prueba/urls.py
from django.urls import path, re_path
from .import views


urlpatterns = [
    path('',views.index,name='index'),
    path('prueba/lista',views.listar_libros,name='lista_libros'),
    path("prueba/libro/<int:id_libro>/", views.dame_libro,name="dame_libro"),
    path("prueba/libro/<int:anyo_libro>/<int:mes_libro>", views.dame_libros_fecha,name="dame_libros_fecha"),
    path("prueba/libro/<str:tipo>/", views.dame_libros_idioma,name="dame_libros_idioma"),
    path("prueba/<int:id_biblioteca>/libro/<str:texto_libro>",views.dame_libros_biblioteca,name="dame_libros_biblioteca"),
    path("ultimo-cliente-libro/<int:libro>",views.dame_ultimo_cliente_libro,name="ultimo_cliente_libro"),
    re_path(r"^filtro[0-9]$",views.libros_no_prestados,name="libros_no_prestados"),
    path('dame-agrupaciones-puntos-clientes',views.dame_agrupaciones_puntos_cliente,name="dame_agrupaciones_puntos_cliente"),
    path('prueba/<int:id_biblioteca>/', views.dame_biblioteca, name='dame_biblioteca'),  
]

prueba/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Biblioteca(models.Model):
    nombre=models.CharField(max_length=100)
    direccion=models.TextField()
    
class Autor(models.Model):
    nombre=models.CharField(max_length=100)
    apellidos=models.CharField(max_length=200,blank=True)
    edad=models.IntegerField(null=True)
    
class Libro(models.Model):
    IDIOMAS = [
        ("ES","Español"),
        ("EN","Inglés"),
        ("FR","Francés"),
        ("IT","Italiano"),
    ]
    
    nombre= models.CharField(max_length=200)
    tipo=models.CharField(
        max_length=2,
        choices=IDIOMAS,
        default="ES",
    )
    descripcion=models.TextField()
    fecha_publicacion=models.DateField()
    Biblioteca=models.ForeignKey(Biblioteca,on_delete=models.CASCADE,related_name="libros_biblioteca")
    autores =   models.ManyToManyField(Autor)
    
class Cliente(models.Model):
    nombre=models.CharField(max_length=100)
    email=models.CharField(max_length=200,unique=True)
    puntos=models.FloatField(default=5.0,db_column="puntos_biblioteca")
    libros=models.ManyToManyField(Libro,through='Prestamos',related_name="libro")
    libros_preferidos=models.ForeignKey(Libro,on_delete=models.CASCADE,related_name="favoritos") #solo se tiene un libro preferido
    def __str__(self):
        return self.nombre
    
class DatosCliente(models.Model):
    cliente = models.OneToOneField(Cliente,on_delete=models.CASCADE)
    direccion=models.TextField()
    gustos=models.TextField()
    telefono=models.IntegerField()
    def __str__(self):
       return "Datos de "+self.cliente.nombre
    
    
class Prestamos(models.Model):
    cliente = models.ForeignKey(Cliente,on_delete=models.CASCADE)
    libro=models.ForeignKey(Libro,on_delete=models.CASCADE)
    fecha_prestamo=models.DateTimeField(default=timezone.now)
    

prueba/views.py
from django.shortcuts import render
from .models import *
from django.db.models import Q,Prefetch
from django.db.models import Avg,Max,Min
from django.views.defaults import page_not_found
# Create your views here.
def index(request):
    bibliotecas = Biblioteca.objects.all()  # Obtiene todas las bibliotecas
    return render(request, 'index.html', {'bibliotecas': bibliotecas})

def listar_libros(request):
    libros=Libro.objects.select_related("Biblioteca").prefetch_related("autores")
    libros=libros.all()
    return render(request,'prueba/lista.html',{"libros_mostrar":libros})
    
def dame_libro(request,id_libro):
    libro=Libro.objects.select_related("Biblioteca").prefetch_related("autores").get(id=id_libro)
    return render(request,'prueba/libro.html',{"libro_mostrar":libro})

def dame_libros_fecha(request,anyo_libro,mes_libro):
    libros=Libro.objects.select_related("Biblioteca").prefetch_related("autores")
    libros=libros.filter(fecha_publicacion__year=anyo_libro,fecha_publicacion__month=mes_libro)
    return render(request,'prueba/libro.html',{"libro_mostrar":libros})  

def dame_libros_idioma(request,tipo):
    libros=Libro.objects.select_related("Biblioteca").prefetch_related("autores")
    libros=libros.filter(Q(tipo=tipo) | Q(tipo="ES") | Q(fecha_publicacion__year="2024") ).order_by("fecha_publicacion") #q de query es para buscar y si quiero añadir otra condicion puedo ponerla
    return render(request,'prueba/lista.html',{"libros_mostrar":libros})
  
def dame_libros_biblioteca(request,id_biblioteca,texto_libro):
    libros=Libro.objects.select_related("Biblioteca").prefetch_related("autores")
    libros=libros.filter(Biblioteca=id_biblioteca).filter(descripcion__contains=texto_libro).order_by("-nombre")
    return render(request,'prueba/lista.html',{"libros_mostrar":libros})  
def dame_ultimo_cliente_libro(request,libro):
    cliente=Cliente.objects.filter(prestamos__libro=libro).order_by("-prestamos__fecha_prestamo")[:1].get()
    return render(request,'prueba/cliente.html',{"cliente":cliente})   #esto es para acceder a las talas intermedias
def libros_no_prestados(request):
    libros=Libro.objects.select_related("Biblioteca").prefetch_related("autores")
    libros=libros.filter(prestamos=None)
    return render(request,'prueba/lista.html',{"libros_mostrar":libros})  
def dame_agrupaciones_puntos_cliente(request):
    resultado = Cliente.objects.aggregate(Avg("puntos"), Max("puntos"), Min("puntos"))
    media=resultado["puntos__avg"]
    maximo=resultado["puntos__max"]
    minimo=resultado["puntos__min"]
    return render(request,'prueba/agrupaciones.html',{"media":media,"maximo":maximo,"minimo":minimo})
def dame_biblioteca(request,id_biblioteca):
    biblioteca=Biblioteca.objects.prefetch_related(Prefetch("libros_biblioteca")).get(id=id_biblioteca)
    return render(request,'prueba/biblioteca.html',{"biblioteca":biblioteca})

#errores
def mi_error_404(request, exception=None):
    return render(request, 'prueba/errores/404.html', None,None,404)

prueba/templates/index.html
<html>
    <head><head>
        <body>
            <h1>BIBLIOTECA ONLINE</h1>

            <h2>Listado de enlaces</h2>
          
            <ul>
                <li>  <a href="{% url 'lista_libros' %}">Libros</a></li>
                <li><a href="{% url 'dame_libro' 10 %}">Ver libro</a></li>
                <li><a href="{% url 'dame_libros_biblioteca' 15 'capital' %}">Libro 15</a></li>
                <li><a href="{% url 'libros_no_prestados' %}">Libro con filtro</a></li>
                <li><a href="{% url 'dame_agrupaciones_puntos_cliente' %}">Agrupaciones de Puntos de Clientes</a></li>
                <h2>Bibliotecas</h2>
                <ul>
                    {% for biblioteca in bibliotecas %}
                        <li><a href="{% url 'dame_biblioteca' biblioteca.id %}">{{ biblioteca.nombre }}</a></li>
                    {% endfor %}
                </ul>
            </ul>
            </ul>
        </body>
</html>

prueba/templates/prueba/agrupaciones.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregaciones de Puntos</title>
</head>
<body>
    <div class="container">
        <h1>Agregaciones de Puntos de Clientes</h1>
        <table>
            <thead>
                <tr>
                    <th>Media de Puntos</th>
                    <th>Punto Máximo</th>
                    <th>Punto Mínimo</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ media }}</td>
                    <td>{{ maximo }}</td>
                    <td>{{ minimo }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

prueba/templates/prueba/biblioteca.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca</title>
</head>
<body>
    <h1>Biblioteca</h1>

 
    
        <div>
            <time>Nombre:{{biblioteca.nombre}}</time>
            <h2>Email:{{biblioteca.email}}</h2>
            <h3>Libros</h3>
            {%for libro in biblioteca.libros_biblioteca.all %}
                <li>{{ libro.nombre }}</li>
            {% endfor%}
        </div>


</body>
</html>

prueba/templates/prueba/cliente.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Página de Ejemplo</title>
</head>
<body>
    <header>
        <h1>Bienvenido a mi página de ejemplo</h1>
    </header>

 
    
        <article>
            <time>Nombre:{{cliente.nombre}}</time>
            <h2>Email:{{cliente.email}}</h2>
            <p>Puntos:{{cliente.puntos}}</p>
        </article>


</body>
</html>

prueba/templates/prueba/libro.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Página de Ejemplo</title>
</head>
<body>
    <header>
        <h1>Bienvenido a mi página de ejemplo</h1>
    </header>

    
        <article>
            <time>Nombre:{{libro_mostrar.nombre}}</time>
            <h2><a href="">{{libro_mostrar.biblioteca.nombre}}</a></h2>
            <p>Autores</p>
        </article>
    

   <ul>
    {% for autor in libro_mostrar.autores.all %}
    <li>{{autor.nombre}}</li>
    {% endfor %}
   </ul>

    <main>
        
        <p>Idioma : {{libro_mostrar.get_tipo_display}}</p>
   
   
        <p>Descripcion {{libro_mostrar.descripcion}}</p>
        <p>Fecha publicacion {{libro_mostrar.fecha_publicacion}}
            <a href="{% url 'dame_libros_fecha' libro_mostrar.fecha_publicacion.year libro_mostrar.fecha_publicacion.month %}">
                Pulsa para ver mas libros del mismo año y mes
            </a>
        </p>
    </main>

</body>
</html>

prueba/templates/prueba/lista.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Página de Ejemplo</title>
</head>
<body>
    <header>
        <h1>Bienvenido a mi página de ejemplo</h1>
    </header>

    {% for libro in libros_mostrar %}  
    
        <article>
            <time>Nombre:{{libro.nombre}}</time>
            <h2><a href="">{{libro.biblioteca.nombre}}</a></h2>
            <p>Autores</p>
        </article>
    

   <ul>
    {% for autor in libro.autores.all %}
    <li>{{autor.nombre}}</li>
    {% endfor %}
   </ul>

    <main>
        <p>Fecha Publiocacion {{libro.fecha_publicacion}}</p>
        <p>Idioma : {{libro.get_tipo_display}}</p>
    </main>
    <footer>
        <p>Descripcion {{libro.descripcion}}</p>
    </footer>
    <a href="{% url 'dame_libro' libro.id %}">Pulsa para ver mas detalles del libro</a>
    <a href="{% url 'dame_libros_idioma' libro.tipo %}">
        Pulsa para ver libros del mismo idioma o Español</a>
        <h3>
            Ultimo cliente que se llevo el libro
            <a href="{% url 'ultimo_cliente_libro' libro.id %}">
            PULSA PARA VERLO
            </a>
    {% endfor %}


  
</body>
</html>